export const FETCH_NEW_RELEASES = 'FETCH_NEW_RELEASES';
export const FETCH_NEW_RELEASES_ERR = 'FETCH_NEW_RELEASES_ERR';

export const FETCH_FEATURED_PLAYLISTS = 'FETCH_FEATURED_PLAYLISTS';
export const FETCH_FEATURED_PLAYLISTS_ERR = 'FETCH_FEATURED_PLAYLISTS_ERR';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_ERR = 'FETCH_CATEGORIES_ERR';
